version: '3.7'

services:

  ccf-db:
    stdin_open: true
    tty: true
    restart: always
    image: odehan/ccf-db
    links:
      - ccf-db-backend
    ports:
      - 80:3000

  ccf-db-backend:
    stdin_open: true
    tty: true
    restart: always
    image: odehan/ccf-db-backend
    links:
      - mongo

  mongo:
    image: mongo
    restart: always
    volumes: 
      - ./data:/data/db
