version: '3.7'

services:

  ccf-db:
    stdin_open: true
    tty: true
    restart: always
#    image: odehan/ccf-db
    build: ./ccf-db
    links:
      - ccf-db-backend:backend
    ports:
      - 80:3000

  ccf-db-backend:
    stdin_open: true
    tty: true
    restart: always
#    image: odehan/ccf-db-backend
    build: ./ccf-db-backend
    links:
      - mongo:mongo
      - es:elasticsearch

  es:
    build: ./es
    restart: always
    environment:
      - network.host=0.0.0.0
    ports:
      - 9233:9200
    volumes:
      - ./data_es:/usr/share/elasticsearch/data

  mongo:
    image: mongo
    restart: always
    volumes: 
      - ./data:/data/db
